global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3005']

  - job_name: 'user'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'auth'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'reservation'
    static_configs:
      - targets: ['host.docker.internal:3006']

  - job_name: 'payment'
    static_configs:
      - targets: ['host.docker.internal:3003']

  - job_name: 'room'
    static_configs:
      - targets: ['host.docker.internal:3004']

# Expose Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
 
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:9419']

  - job_name: 'github_actions'
    # Placeholder for a GitHub Actions exporter (optional). If you deploy a
    # GitHub Actions exporter, change the target accordingly.
    static_configs:
      - targets: ['github-exporter:9118']
